pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Setup Python Environment') {
            steps {
                sh 'python -m venv venv'
                sh '. venv/bin/activate'
                sh 'pip install -r requirements.txt'
            }
        }

        stage('Run Validation Tests') {
            steps {
                sh '. venv/bin/activate'
                sh 'python manage.py test'
            }
        }
    }

    post {
        always {
            echo 'Cleaning up...'
            sh 'rm -rf venv' // Clean up virtual environment
        }
        success {
            echo 'Validation succeeded. Ready for deployment.'
        }
        failure {
            echo 'Validation failed.'
        }
    }
}
