pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Setup Python Environment') {
            steps {
                dir('DressUp') {  // Navigate into the DressUp directory
                    sh 'python3 -m venv venv'
                    sh '''
                    . venv/bin/activate
                    pip install -r requirements.txt
                    '''
                }
            }
        }

        stage('Run Validation Tests') {
            steps {
                dir('DressUp') {  // Ensure you are still in the DressUp directory
                    sh '''
                    . venv/bin/activate
                    python manage.py test
                    '''
                }
            }
        }
    }

    post {
        always {
            dir('DressUp') {  // Ensure you clean up the virtual environment within the DressUp directory
                echo 'Cleaning up...'
                sh 'rm -rf venv'
            }
            echo 'Pipeline execution completed.'
        }
        success {
            echo 'Validation succeeded.'
        }
        failure {
            echo 'Validation failed.'
        }
    }
}
