name: Docker Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Trigger Jenkins and Wait for Completion
      run: |
        # Fetch the crumb
        crumb=$(curl -s -u ${{ secrets.JENKINS_USER }}:${{ secrets.JENKINS_TOKEN }} "http://3.75.204.56:8080/crumbIssuer/api/xml?xpath=concat(//crumbRequestField,\":\",//crumb)")
        echo "Crumb received: $crumb"

        # Trigger the Jenkins job
        trigger_response=$(curl -X POST "http://3.75.204.56:8080/job/ValidationPipeline/build?token=${{ secrets.JENKINS_TOKEN }}" -u ${{ secrets.JENKINS_USER }}:${{ secrets.JENKINS_TOKEN }} -H "$crumb")
        echo "Jenkins job triggered: $trigger_response"

        # Initialize timeout variables
        timeout=0
        max_timeout=1800  # Set a maximum timeout in seconds (e.g., 30 minutes).

        # Poll for job completion
        while [ $timeout -lt $max_timeout ]; do
          # Fetch the job status
          response=$(curl -s -u ${{ secrets.JENKINS_USER }}:${{ secrets.JENKINS_TOKEN }} -H "$crumb" "http://3.75.204.56:8080/job/ValidationPipeline/lastBuild/api/json")
          echo "Response from Jenkins: $response"
          status=$(echo $response | jq -r '.result')
          echo "Parsed status: $status"

          # Check the job status
          if [ "$status" == "SUCCESS" ]; then
            echo "Jenkins job succeeded."
            break
          elif [ "$status" == "FAILURE" ]; then
            echo "Jenkins job failed."
            exit 1
          elif [ "$status" == "null" ]; then
            echo "Jenkins job is still running..."
          else
            echo "Received unexpected status."
          fi

          # Sleep and update timeout
          sleep 30
          timeout=$((timeout + 30))
        done

        # Handle timeout situation
        if [ $timeout -ge $max_timeout ]; then
          echo "Timed out waiting for Jenkins job to complete."
          exit 1
        fi
      env:
        JENKINS_USER: ${{ secrets.JENKINS_USER }}
        JENKINS_TOKEN: ${{ secrets.JENKINS_TOKEN }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_TOKEN }}" | docker login -u jadharfoush --password-stdin

    - name: Build and Push Docker Image
      run: |
        docker buildx build --platform linux/amd64 -t jadharfoush/chooseyourdress:latest --push .
      working-directory: ./DressUp

    - name: Deploy to Machine 1
      run: |
        ssh -o StrictHostKeyChecking=no -i ${{ secrets.SSH_PRIVATE_KEY }} ubuntu@3.74.162.139 "docker pull jadharfoush/chooseyourdress:latest && docker run -d --name chooseyourdress -p 8000:8000 jadharfoush/chooseyourdress:latest"
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Deploy to Machine 2
      run: |
        ssh -o StrictHostKeyChecking=no -i ${{ secrets.SSH_PRIVATE_KEY }} ubuntu@18.199.67.122 "docker pull jadharfoush/chooseyourdress:latest && docker run -d --name chooseyourdress -p 8000:8000 jadharfoush/chooseyourdress:latest"
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
