name: Docker Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build Docker Image
      run: docker buildx build --platform linux/amd64 -t jadharfoush/my-django-app:latest .
      env:
        DOCKER_USERNAME: jadharfoush
        DOCKER_PASSWORD: Jad22030201
      working-directory: ./DressUp

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: jadharfoush
        password: Jad22030201

    - name: Push Docker Image
      run: docker push jadharfoush/my-django-app:latest
      env:
        DOCKER_USERNAME: jadharfoush
        DOCKER_PASSWORD: Jad22030201
